Assignment -> Numpy

In [1]:
import numpy as np
import pandas as pd

In [2]:
#1. How to Creating a 3x3 Identity Matrix with Float Data Type? 

a=np.identity(3,'float')

a.dtype



dtype('float64')

In [3]:
#2. Create a 1D Array with Random Values between 0 and 1. 
b=np.random.random(8)
b

array([0.62697603, 0.87160575, 0.38272771, 0.36632878, 0.4178544 ,
       0.5712695 , 0.06030623, 0.45889983])

In [4]:
#3.Create a 2D Array with Random Integer Values. 
a = np.random.randint(0,10,10).reshape(5,2)
a

array([[2, 3],
       [1, 0],
       [2, 5],
       [8, 1],
       [6, 5]], dtype=int32)

In [5]:
#4.Creating an Array Using a Custom Function.

def custom_array():
    c_array = np.random.random(10)
    return c_array

custom_array()

array([0.7622256 , 0.8426077 , 0.01892684, 0.44099161, 0.71401411,
       0.07028621, 0.93332129, 0.65806325, 0.79830129, 0.63328902])

In [6]:
#5.Reshaping a 1D Array into a 2D Array 

a=np.random.random(10)
a
a.reshape(5,2)

array([[0.7046801 , 0.10757582],
       [0.6450744 , 0.21026684],
       [0.51392745, 0.83934395],
       [0.87524869, 0.90200135],
       [0.9432114 , 0.0921033 ]])

In [7]:
#6. How to Creating a 3x3 Array of Ones? 

b = np.ones((3,3),"i")
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [8]:
#7.How to get the common items between two pythons NumPy? 
'''Input: 
a = np. array ([1,2,3,2,3,4,3,4,5,6]) 
b = np. array ([7,2,10,2,7,4,9,4,9,8]) 
Expected Output: 
array ([2, 4]) '''

a = np. array ([1,2,3,2,3,4,3,4,5,6]) 
b = np. array ([7,2,10,2,7,4,9,4,9,8]) 

common_array = np.intersect1d(a,b)
common_array





array([2, 4])

In [9]:
#8. From array a remove all items present in array b Input: 
'''a = np. array ([1,2,3,4,5]) 
b = np. array ([5,6,7,8,9]) 
Expected Output: 
array ([1,2,3,4] '''

a = np. array ([1,2,3,4,5]) 
b = np. array ([5,6,7,8,9]) 

result = np.setdiff1d(a,b)
result



array([1, 2, 3, 4])

In [10]:
#9. Limit the number of items printed in python NumPy array a to a maximum of 6 elements. 
'''a = np. arrange (15) 
Expected Output: 
array ([ 0, 1, 2, ..., 12, 13, 14] '''

a = np.arange(15) 
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14], shape=(15,))

In [11]:
#10. Drop all nan values from a 1D NumPy array Input: 
'''np. array ([1,2,3, np.nan,5,6,7, np.nan]) 
Desired Output: 
array ([ 1., 2., 3., 5., 6., 7.]) '''

a = np. array ([1,2,3, np.nan,5,6,7, np.nan])
nan = ~np.isnan(a)

result = a[nan]
result


array([1., 2., 3., 5., 6., 7.])

In [12]:
#11. Create a 1D NumPy array of the first 20 natural numbers and a 2D NumPy array of shape (4, 5) with values ranging from 1 to 20. 

a =np.arange(20)
a
b=np.arange(1,21).reshape(4,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], shape=(4, 5))

In [67]:
#12.Given a 3D NumPy array of shape (2, 3, 4), find its shape, size, number of dimensions, and data type. Change its data type to float64 and verify 
#the change. 

a = np.arange(24).reshape(2,3,4)
print("shape :-",a.shape)
print()
print("size :-",a.size)
print()
print("number of dimension :-",a.ndim)
print()
print("datatype:-",a.dtype)
print()

b=a.astype(np.float64)
print("datatype :-",b.dtype)


shape :- (2, 3, 4)

size :- 24

number of dimension :- 3

datatype:- int64

datatype :- float64


In [66]:
#13.  Reshape a 1D array of 12 elements into a 3x4 2D array and then flatten it back into a 1D array using ravel (). Verify that the flattened array 
#matches the original. 

a = np.arange(12)
print("1D array is :-", a)
print()
b = a.reshape(3,4)
print("2D array is :-",b)
print()
c=np.ravel(b)
print("Flattened array is :-", c)

1D array is :- [ 0  1  2 ...  9 10 11]

2D array is :- [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array is :- [ 0  1  2 ...  9 10 11]


In [65]:
#14.Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4, 5, 6]), perform element-wise addition, subtraction, multiplication, and 
#division. Explain the behavior when dividing by zero.

a = np. array ([1, 2, 3])
b = np. array ([4, 5, 6])

# Addition
add = a+b
print("Addition :-",add)
print()

# Subtraction
sub = a-b
print("Subtraction :-",sub)
print()

# Multiplication
mul = a*b
print("Multiplication :-",mul)
print()

# Division
div = a/b
print("Division :-",div)
print()

c = np.array([10,20,30])
d = np.array([10,10,0])

div = c/d
print(div)
# inf -> stands for infinity when non zero number divide by zero it gives inf ,whereas it gives NaN when zero number divide by zero.



Addition :- [5 7 9]

Subtraction :- [-3 -3 -3]

Multiplication :- [ 4 10 18]

Division :- [0.25 0.4  0.5 ]

[ 1.  2. inf]


C:\Users\mjmak\AppData\Local\Temp\ipykernel_8588\4013621149.py:30: RuntimeWarning: divide by zero encountered in divide
  div = c/d


In [16]:
#15. Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform element-wise addition using broadcasting. Explain how broadcasting rules apply 
#in this scenario.

a = np.arange(3).reshape(3,1) 
print("array a is :-",a)
b = np.arange(3)
print("array b is :-",b)

add = a+b
add

array a is :- [[0]
 [1]
 [2]]
array b is :- [0 1 2]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]], shape=(3, 3))

In [17]:
#16.Generate a random 2D array of integers between 0 and 10. Use conditional operators to create a Boolean mask identifying elements greater than 
#5. Replace all elements greater than 5 with the value 5.

a = np.arange(10).reshape(2,5)
a

mask = a>5
mask

a[mask]=5

a


array([[0, 1, 2, 3, 4],
       [5, 5, 5, 5, 5]], shape=(2, 5))

In [64]:
#17.  Given a 4x4 array of random integers, use indexing and slicing to extract: 
'''o The entire second row 
o The last column 
o The subarray consisting of the first two rows and first two columns '''

a = np.arange(16).reshape(4,4)
print("Array is :- \n",a)
print()

print("Entire second row is :-",a[1::3])
print()

print("Last column is :-",a[:,-1])

a[:2,:2]

Array is :- 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Entire second row is :- [[4 5 6 7]]

Last column is :- [ 3  7 11 15]


array([[0, 1],
       [4, 5]])

In [24]:
#18.  Describe a practical example where NumPy can be used in EDA, AI, ML, and DL, and implement a NumPy solution for a simple task in each 
#area. 

#EDA - You have survey data with some missing values, and you want to replace them with the mean

# Survey age data with missing values (NaN)
ages = np.array([25, 30, np.nan, 22, 28, np.nan, 35])

# Find mean without NaN
mean_age = np.nanmean(ages)

# Replace NaN with mean
ages_cleaned = np.where(np.isnan(ages), mean_age, ages)

print("Cleaned ages:", ages_cleaned)

# AI - A basic AI system to recommend “Hot” or “Cold” drink based on temperature

temperature_data = np.array([15, 32, 28, 10, 35])  # in °C

# AI decision: if temp >= 25°C → "Cold drink", else → "Hot drink"
recommendation = np.where(temperature_data >= 25, "Cold drink", "Hot drink")

print("Recommendations:", recommendation)

# ML - Scaling features between 0 and 1 before feeding them to a model.

features = np.array([[50, 2000],
                     [20, 1200],
                     [30, 1500]])

# Min-Max normalization
min_vals = features.min(axis=0)
max_vals = features.max(axis=0)
normalized_features = (features - min_vals) / (max_vals - min_vals)

print("Normalized features:\n", normalized_features)

# DL - Converting integer class labels into one-hot vectors (common in neural networks).

labels = np.array([0, 2, 1, 2])  # Class IDs
num_classes = 3

# One-hot encoding
one_hot_labels = np.eye(num_classes)[labels]

print("One-hot labels:\n", one_hot_labels)





Cleaned ages: [25. 30. 28. ... 28. 28. 35.]
Recommendations: ['Hot drink' 'Cold drink' 'Cold drink' 'Hot drink' 'Cold drink']
Normalized features:
 [[1.         1.        ]
 [0.         0.        ]
 [0.33333333 0.375     ]]
One-hot labels:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#19. Create a random 4x4 matrix and use NumPy to compute its eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the matrix. 


# Create a random 4x4 matrix
A = np.random.rand(4, 4)

print("Original Matrix A:\n", A)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

# Reconstruct the matrix: A = V * D * V_inv
D = np.diag(eigenvalues)            # Diagonal matrix of eigenvalues
V = eigenvectors
V_inv = np.linalg.inv(V)

A_reconstructed = V @ D @ V_inv

print("\nReconstructed Matrix A:\n", A_reconstructed)

# Verify (allowing for small floating-point errors)
print("\nDifference between A and A_reconstructed:\n", A - A_reconstructed)


Original Matrix A:
 [[0.8116126  0.02944906 0.19812665 0.71505017]
 [0.33061869 0.79642287 0.46535245 0.31690545]
 [0.68726397 0.2003618  0.41986644 0.59419095]
 [0.00991441 0.35686513 0.89291081 0.86252507]]

Eigenvalues:
 [1.94644203+0.j         0.27635833+0.22524407j 0.27635833-0.22524407j
 0.39126829+0.j        ]

Eigenvectors:
 [[ 0.45447013+0.j         -0.49091225-0.23835694j -0.49091225+0.23835694j
   0.50453108+0.j        ]
 [ 0.48427616+0.j          0.29984194+0.23597176j  0.29984194-0.23597176j
  -0.62032517+0.j        ]
 [ 0.48846202+0.j         -0.48502773+0.05076224j -0.48502773-0.05076224j
   0.4513776 +0.j        ]
 [ 0.56598441+0.j          0.56460125+0.j          0.56460125-0.j
  -0.39611025+0.j        ]]

Reconstructed Matrix A:
 [[0.8116126 -3.80082341e-17j 0.02944906+8.77197055e-17j
  0.19812665-8.87351577e-18j 0.71505017+2.29360650e-17j]
 [0.33061869-1.48712018e-17j 0.79642287+1.56617487e-16j
  0.46535245+5.80008914e-17j 0.31690545+1.24811739e-16j]
 [0.68726397-2.4

In [33]:
#20. Create a 1D array of 27 elements and reshape it into a 3x3x3 3D array. Flatten it back into a 1D array and compare the flattened array with the original. 

a=np.arange(27)
print("1D array is :- \n",a)

# reshape into 3*3*3
b=a.reshape(3,3,3)
print("3D array is :- \n",b)

# Flatten array in 1D
c =b.ravel()
print("Flatten array in 1D is :- \n",c)




1D array is :- 
 [ 0  1  2 ... 24 25 26]
3D array is :- 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Flatten array in 1D is :- 
 [ 0  1  2 ... 24 25 26]


In [63]:
#21. : Perform matrix multiplication of two 2D arrays using np.dot () and @. Compare the results and performance of both methods using a large dataset.

import time

A = np.random.rand(1000, 500)
B = np.random.rand(500, 800)

#using dot
start_dot = time.time()
result_dot = np.dot(A, B)
end_dot = time.time()

#using @
start_at = time.time()
result_at = A @ B
end_at = time.time()

#compare result
print("Are results identical?", np.allclose(result_dot, result_at))
print()

# Compare performance
print(f"np.dot() time: {end_dot - start_dot:.6f} seconds")
print(f"@ operator time: {end_at - start_at:.6f} seconds")


Are results identical? True

np.dot() time: 0.010544 seconds
@ operator time: 0.007107 seconds


In [44]:
#22.  Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4, 1). Perform an element-wise operation using broadcasting and explain the result. Use np. new axis to achieve the same result without broadcasting. 

a = np.arange(8).reshape(2,1,4)
b = np.arange(4).reshape(4,1)

print("3D array shape:", a.shape)
print("2D array (reshaped to 1D) shape:", b.shape)

#broadcast
result = a+b  
print("\nResult with broadcasting:\n", result)
print("Shape after broadcasting:", result.shape)

#using np.newaxis
b_new = b[np.newaxis, np.newaxis, :]  # shape (1, 1, 4)
result_newaxis = a + b_new
print("\nResult with np.newaxis:\n", result_newaxis)
print("Shape after np.newaxis:", result_newaxis.shape)

3D array shape: (2, 1, 4)
2D array (reshaped to 1D) shape: (4, 1)

Result with broadcasting:
 [[[ 0  1  2  3]
  [ 1  2  3  4]
  [ 2  3  4  5]
  [ 3  4  5  6]]

 [[ 4  5  6  7]
  [ 5  6  7  8]
  [ 6  7  8  9]
  [ 7  8  9 10]]]
Shape after broadcasting: (2, 4, 4)

Result with np.newaxis:
 [[[[ 0  1  2  3]
   [ 1  2  3  4]
   [ 2  3  4  5]
   [ 3  4  5  6]]

  [[ 4  5  6  7]
   [ 5  6  7  8]
   [ 6  7  8  9]
   [ 7  8  9 10]]]]
Shape after np.newaxis: (1, 2, 4, 4)


In [62]:
#23.  Generate a 2D array of random floats between 0 and 1. Use conditional operators to create a Boolean mask for values less than 0.5. Replace these values with their squares and leave the rest unchanged. 

a = np.random.rand(4,5)
print("2D array is :\n",a)
print()

mask = a<0.5

a[mask] = a[mask]**2

print("New array is :\n",a)



2D array is :
 [[0.22967898 0.60368004 0.48417626 0.81897402 0.50543123]
 [0.08323112 0.93500244 0.29790587 0.95765037 0.11935668]
 [0.66400288 0.66423618 0.06536051 0.06595654 0.71423485]
 [0.50644322 0.47409779 0.81733955 0.18012424 0.14969763]]

New array is :
 [[0.05275243 0.60368004 0.23442665 0.81897402 0.50543123]
 [0.00692742 0.93500244 0.08874791 0.95765037 0.01424602]
 [0.66400288 0.66423618 0.004272   0.00435026 0.71423485]
 [0.50644322 0.22476871 0.81733955 0.03244474 0.02240938]]


In [61]:
#24. Given a 5x5 array of sequential integers, use slicing to: 
'''o Extract the diagonal elements 
o Replace the elements of the middle row with zeros 
o Flip the array vertically and horizontally '''

a = np.arange(1,26).reshape(5,5)
print("Array is :\n",a)
print()

diagonal = a[np.arange(5),np.arange(5)]
print("Diagonal of an array is:- \n",diagonal)
print()

a[2,:] = 0
print("Array after replacing with zero is :\n",a)
print()

flipped = a[::-1,::-1]
print("Array after flipping is:\n",flipped)

Array is :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Diagonal of an array is:- 
 [ 1  7 13 19 25]

Array after replacing with zero is :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 0  0  0  0  0]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array after flipping is:
 [[25 24 23 22 21]
 [20 19 18 17 16]
 [ 0  0  0  0  0]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [73]:
#25 . Create a 4D array of shape (2, 3, 4, 5) with random integers. Use advanced slicing to extract a subarray and compute the mean along a specified axis. 

a = np.random.randint(0, 10, size=(2, 3, 4, 5))
print("Array is :-",a)
print()

s_array = a[0, 1:3, 0:3, :]
print('Subarray is :-',s_array)
print()

mean_axis2 = np.mean(s_array, axis=2)
print("Mean along a 2 axis is:-",mean_axis2)

Array is :- [[[[7 0 3 0 7]
   [7 2 6 8 5]
   [5 1 0 3 7]
   [4 4 2 7 2]]

  [[3 9 9 7 5]
   [1 6 3 9 0]
   [3 2 7 3 4]
   [9 8 8 0 1]]

  [[1 4 5 6 4]
   [4 5 2 9 5]
   [1 9 5 2 0]
   [7 7 6 1 7]]]


 [[[3 6 1 2 8]
   [1 2 1 2 3]
   [1 0 2 6 0]
   [6 5 6 4 7]]

  [[5 4 4 2 4]
   [5 5 9 2 1]
   [7 8 1 4 9]
   [1 8 9 0 2]]

  [[3 6 8 0 1]
   [3 2 4 4 2]
   [3 2 3 1 3]
   [3 1 8 6 4]]]]

Subarray is :- [[[3 9 9 7 5]
  [1 6 3 9 0]
  [3 2 7 3 4]]

 [[1 4 5 6 4]
  [4 5 2 9 5]
  [1 9 5 2 0]]]

Mean along a 2 axis is:- [[6.6 3.8 3.8]
 [4.  5.  3.4]]


In [ ]:
#26.Given an array of shape (10, 20), reshape it to (20, 10) and (5, 40). Discuss the impact on the array's shape, size, and dimensionality.

a = np.arange(200).reshape(10,20)
print("Array with shape (10,20) is :- \n",a)
print()

b =a.reshape(20,10)
print("Array with shape (20,10) is :- \n",b)
print()

c=a.reshape(5,40)
print("Array with shape (5,40) is :- \n",c)


# When we reshape array with diffrent shape then it changes visually as only number of rows and column change not the number of element. So it remains in same dimension  and only shape gets change.

Array with shape (10,20) is :- 
 [[  0   1   2 ...  17  18  19]
 [ 20  21  22 ...  37  38  39]
 [ 40  41  42 ...  57  58  59]
 ...
 [140 141 142 ... 157 158 159]
 [160 161 162 ... 177 178 179]
 [180 181 182 ... 197 198 199]]

Array with shape (20,10) is :- 
 [[  0   1   2 ...   7   8   9]
 [ 10  11  12 ...  17  18  19]
 [ 20  21  22 ...  27  28  29]
 ...
 [170 171 172 ... 177 178 179]
 [180 181 182 ... 187 188 189]
 [190 191 192 ... 197 198 199]]

Array with shape (5,40) is :- 
 [[  0   1   2 ...  37  38  39]
 [ 40  41  42 ...  77  78  79]
 [ 80  81  82 ... 117 118 119]
 [120 121 122 ... 157 158 159]
 [160 161 162 ... 197 198 199]]


In [92]:
#27. Generate a large 2D array and demonstrate the use of np. reshape () and unravel () to manipulate its shape for various linear algebra operations. 

a = np.random.randint(1,100, size=(100,50))
print("Shape of Array is :- ",a.shape)
print()

a_t = a.reshape(50,100)
product = np.dot(a,a_t)
print("Shape after reshape Array is:",a_t.shape)
print()
print("Product shape is :",product.shape)
print()

#unravel()
max_i_flat = np.argmax(a) #index in flattened array
con = np.unravel_index(max_i_flat,a.shape)

print("Max value:-",a[con])
print("Max value coordinates:",con)

Shape of Array is :-  (100, 50)

Shape after reshape Array is: (50, 100)

Product shape is : (100, 100)

Max value:- 99
Max value coordinates: (np.int64(0), np.int64(36))


In [93]:
#28. Given a 6x6 matrix, use advanced indexing and slicing to extract the upper triangular part of the matrix and set the lower triangular part to zero. Verify the result.

# Create a 6x6 matrix
A = np.arange(1, 37).reshape(6, 6)
print("Original matrix:\n", A)

# Set lower triangular part to zero (keep upper triangle)
A_upper = np.triu(A)
print("\nUpper triangular matrix:\n", A_upper)


Original matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Upper triangular matrix:
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
